### ISSUE TITLE
Linking error if include #include <reactive/ObservableProperty.h> in header

### ISSUE THREAD

**Issue by asyniakov** [tower120/reactive#3]
The problem with static variables inside https://github.com/tower120/reactive/blob/master/src/reactive/details/utils/DeferredForwardContainer.h

Does it mean that user should include reactive headers in cpp only?

**Comment by tower120** [comment]
What kind of problem?

**Comment by asyniakov** [comment]
thx man! very nice library! but I don't understand the fix. how does inline help? is it legal from the standard point of view?

**Comment by tower120** [comment]
See https://en.cppreference.com/w/cpp/language/static :

> A static data member may be declared inline. An inline static data member can be defined in the class definition and may specify an initializer. It does not need an out-of-class definition

IOW, without `inline` initialization **must** be in .cpp file. Like:
```
struct X
{
    static int n = 1;
};
```

```
#include "X.h"
int X::n = 1;
```
