### ISSUE TITLE
DeferredForwardContainer::void foreach(Closure&& closure) conflicts with Qt foreach

### ISSUE THREAD

**Issue by asyniakov** [tower120/reactive#4]
It's not a fault of the library, but it'd be great if you could rename foreach to for_each or smth like that. The problem is that Qt has macro `foreach `and it conflicts with your function 

> template<class Closure>
> void foreach(Closure&& closure) {

as result there are errors in msvc and qt: 

_master\src\reactive\details\utils\deferredforwardcontainer.h(118): warning C4003: not enough arguments for function-like macro invocation 'Q_FOREACH' (compiling source file QtBindings.cpp)
master\src\reactive\details\utils\deferredforwardcontainer.h(118): error C2988: unrecognizable template declaration/definition (compiling source file QtBindings.cpp)
master\src\reactive\details\utils\deferredforwardcontainer.h(126): note: see reference to class template instantiation 'utils::DeferredForwardContainer<T,DeferredActionValue,ActionListLock,ListMutationLock,unordered>' being compiled (compiling source file QtBindings.cpp)_

writing #undef foreach is very annoying before reactive's includes

**Comment by tower120** [comment]
It should be deprecated now https://www.kdab.com/goodbye-q_foreach/
And http://doc.qt.io/qt-5/qtglobal.html#Q_FOREACH : 

> Note: Since Qt 5.7, the use of this macro is discouraged. It will be removed in a future version of Qt. Please use C++11 range-for, possibly with qAsConst(), as needed.

**Comment by asyniakov** [comment]
yes, but it will happen in years :( I'm using 5.11 and it still there

**Comment by tower120** [comment]
Won't fix this.

You can make separate header, which will include all recative headers with #undef foreach :

```
// reactive.h
#pragma once
#undef foreach
#include <reactive/ReactiveProperty.h>
#include <reactive/Event.h>
// ..etc...
```

and include it, instead of reactive headers.
