### ISSUE TITLE
What is the best way to capture ObservableProperty?

### ISSUE THREAD

**Issue by asyniakov** [tower120/reactive#5]
Sorry, I have not found your email, but I'm wondering what is the best way to capture ObservableProperty in lambda? is it better to use by ref, by value or shared_ptr? another question - what is the best way to pass  ObservableProperty to function - by ref, by value or shared_ptr?

**Comment by tower120** [comment]
Why do you want to capture `ObservableProperty` ?

**Comment by asyniakov** [comment]
I wrote class ReactiveLine (that wraps OpenGL stuff inside). It takes two ObservablePropert(ies) by ref - point A, point B in ctor. The idea is to update dynamically line when A or B changes.

**Comment by tower120** [comment]
So you need to depend on two observables simultaneously?
This will not suite your needs https://github.com/tower120/reactive#observe?

**Comment by asyniakov** [comment]
that what I'm doing inside ctor. But I'm rather trying to understand how to "reference"  ObservableProperty from the outside world. 

```
ReactiveLine::ReactiveLine(reactive::ObservableProperty<glm::vec3>& A, reactive::ObservableProperty<glm::vec3>& B, double width)
		: osg::Geometry()
		, A(A)
		, B(B)
	{
		osg::ref_ptr<osg::Vec3Array> vertexArray = new osg::Vec3Array(2);
		osg::ref_ptr<osg::Vec3Array> normalArray = new osg::Vec3Array(2);

		osg::ref_ptr<osg::Vec4Array> colors = new osg::Vec4Array();
		colors->push_back({ 0,0,1,1 });

		(*vertexArray)[0].set(Converters::map(A.getCopy()));
		(*normalArray)[0].set(0, 0, 1);

		(*vertexArray)[1].set(Converters::map(B.getCopy()));
		(*normalArray)[1].set(0, 0, 1);

		osg::Geometry::setUseDisplayList(false);
		osg::Geometry::setUseVertexBufferObjects(true);
		osg::Geometry::setVertexArray(vertexArray);
		osg::Geometry::setNormalArray(normalArray, osg::Array::BIND_PER_VERTEX);
		osg::Geometry::setColorArray(colors, osg::Array::BIND_OVERALL);
		osg::Geometry::addPrimitiveSet(new osg::DrawArrays(osg::PrimitiveSet::LINES, 0, vertexArray->size()));

		osg::ref_ptr<osg::LineWidth> lineWidth = new osg::LineWidth(width);

		auto stateSet = osg::Geometry::getOrCreateStateSet();
		stateSet->setAttributeAndModes(lineWidth);
		stateSet->setMode(GL_LIGHTING, osg::StateAttribute::OFF);

		unsubscribe = reactive::observe([this](glm::vec3 A, glm::vec3 B) {
			osg::Vec3Array* vertices = dynamic_cast<osg::Vec3Array*>(osg::Geometry::getVertexArray());
			(*vertices)[0].set(Converters::map(A));
			(*vertices)[1].set(Converters::map(B));
			vertices->dirty();
		}, A, B);
	}

	ReactiveLine::~ReactiveLine() {
		unsubscribe();
	}
```

**Comment by tower120** [comment]
`ObservableProperty` (and everything else) is stack allocated (no smart_ptr's inside) - so by reference is fine.

**Comment by asyniakov** [comment]
thx! is it ok if I continue to ask questions there or can I reach you by email?

**Comment by tower120** [comment]
And I think you can use const ref here:
```cpp
unsubscribe = reactive::observe([this](const glm::vec3& A, const glm::vec3& B) {
                            ....
		}, A, B);
```

By the way, if your `ReactiveLine` is `shared_ptr` managed - you can try https://github.com/tower120/reactive#bind - it will auto unsubscribe.
